### ISSUE TITLE
Update State of the Art

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2015-CIDS#12]
Including bibliography from GECCO paper.

**Comment by unintendedbear** [comment]
How's this going??

I've found an interesting article which we could include in the State of The Art: http://link.springer.com/article/10.1007/s10462-009-9109-6

**Comment by unintendedbear** [comment]
And this whitepaper, http://projects.puremagic.com/greylisting/whitepaper.html
Also, the solution of the author is implemented in Perl :) (@JJ)

**Comment by JJ** [comment]
Cool!

**Comment by amorag** [comment]
I'll update SotA with some of the references in the GECCO paper.
@zeinebchelly should also add Feature Selection references, and you (@unintendedbear) can include these new references you have stated in previous comments.

In any case, the inclusion of references from GECCO has the aim of 'moving' the paper topics to those closer with the main topic of the book (computational intelligence).

You (@unintendedbear) should support this along the whole text, starting from the abstract and intro, and @zeinebchelly should explain (and support) that Rough Sets are included in CI area, if they are.
This is part of #6, but you can define a new issue for this for the sake of clarity.

If this is not done, the inclusion of most of the GECCO references will have no sense in this paper.

**Comment by unintendedbear** [comment]
But...

> should explain (and support) that Rough Sets are included in CI area, if they are.

And ok, I don't know many about CI but in the very website of the book:

> First-class contributions addressing research challenges in these areas and their CI-based solutions (i.e., neural networks, fuzzy systems, evolutionary computation, swarm intelligence, _rough sets_, granular computing, and other emerging learning or optimization techniques) are solicited.

So I think that we already are inside the topics of the book.

**Comment by amorag** [comment]
Ok, good.

In my view, the paper should change it's orientation, even if RSs have been included.
It was initially thought as a 'pure' DM/ML application, so it should be reoriented to a CI-aimed paper with a DM/ML process inside.

With this aim, I would include along the work more textual references to that field.

But as you wish.

**Comment by unintendedbear** [comment]
Please review @JJ and @amorag
