### ISSUE TITLE
Include results after removing duplicated requests

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2015-CIDS#14]
I have them already from the Master Thesis

**Comment by amorag** [comment]
The results are interesting of course, but take care.
Are you planning to apply FS to these data also?

If not, maybe it could be a critical point for the reviewers to wonder why haven't we used these data (that are better I think) for the FS experiments, and for the rule-based study...

Maybe these results could be considered for the journal paper.

**Comment by amorag** [comment]
I was confused with another dataset, sorry.
Thus, everything is fine.
