### ISSUE TITLE
Review State of the Art

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2015-CIDS#15]
And please fill or write if necessary.

**Comment by JJ** [comment]
OK.

2015-02-26 9:12 GMT+01:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> And please fill or write if necessary.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-CIDS/issues/15.

## 

JJ

**Comment by unintendedbear** [comment]
Hi @amorag , you have two assigned issues. Again, please if you're not going to close them, re-assign them to another person.
