### ISSUE TITLE
Review description of data structure a

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2015-CIDS#19]
When talking about Drools and Weka fiel extensions. Try to describe the data structures in a language-agnostic fashion.

**Comment by unintendedbear** [comment]
Actually, I'm not sure about this... because the reviewer says " It seems a little unnecessary to include low-level details of using the Drools package (is the file extension relevant?). At the point first encountered in the paper, Figure 1 seems unnecessary. Similarly, is the actual format of Weka data files (ARFF) actually relevant? Would it not make sense to describe the data structures in a language-agnostic fashion?"

But it is necessary because the format of the data strongly forces the way of parsing... Should I specify this instead of erasing Drools reference (with its reference to bibliography)? What do you think @JJ @zeinebchelly ?

**Comment by zeinebchelly** [comment]
When talking about Drools in the manuscript, it is not necessary to mention
its basic details
so, as said Fig 1 can be omitted. For the Arff file it is not correct :)
 and still I think it is not necessary to give a sample of the .arff file
as it is known. We can just keep the description of the arff file without
the Fig. 2.
What do you think?

2015-07-20 10:51 GMT+01:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

**Comment by unintendedbear** [comment]
I agree :)
