### ISSUE TITLE
Perform experiments excluding the URL feature from the sets

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2015-CIDS#5]
To test the obtained results without the main feature and also to check the classification rules that the models generate.

**Comment by unintendedbear** [comment]
I completed today with outputs from the classifiers, erasing features: url_core, client IP, and server IP.

**Comment by amorag** [comment]
Ok, thank you, but this was something that I was going to do today.

**Comment by unintendedbear** [comment]
Didn't know, I just saw there was work left to do :)
Still, if you want, you can try running NNge, as I've tried in two different machines and weka just give me the rules, not the accuracy results.

**Comment by amorag** [comment]
Ok, thank you.

I didn’t create an issue for this reason.

I’ll try NNge, then.

De: Paloma de las Cuevas Delgado [mailto:notifications@github.com] 
Enviado el: viernes, 20 de febrero de 2015 12:39
Para: geneura-papers/2015-CIDS
CC: Antonio Mora
Asunto: Re: [2015-CIDS] Perform experiments excluding the URL feature from the sets (#5)

Didn't know, I just saw there was work left to do :)
Still, if you want, you can try running NNge, as I've tried in two different machines and weka just give me the rules, not the accuracy results.

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-CIDS/issues/5#issuecomment-75225496 .  https://github.com/notifications/beacon/AC6-WhlJnKHGCJ3yW3hVZy-YJzKwulw4ks5ntxRIgaJpZM4DioLQ.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4293/9149 - Fecha de publicación: 02/20/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4284/9123 - Fecha de publicación: 02/16/15

**Comment by amorag** [comment]
I have tried also twice and wait for some hours without final results for NNge.
That's strange...

I'll try tomorrow in a better machine.

**Comment by unintendedbear** [comment]
How's this going?

All the discussion on rules will be in its own section, so we'll have Experiments-Results-Rules-Conclusions. Is that ok?

**Comment by unintendedbear** [comment]
Hi, this milestone has ended. Could you please upload the results? Otherwise, please re-assign the issue. Thank you.

**Comment by amorag** [comment]
I'm working on it.

**Comment by amorag** [comment]
I pushed the ENTER while I was writing the description of the commit, sorry.

**Comment by unintendedbear** [comment]
So is closed or not? If it's closed, please warn us about this by opening a new issue for the rest to review.

Thank you.
