### ISSUE TITLE
Reorganize the paper for the extension

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2015-CIDS#6]
Remove superfluous contents, define sections (old and new) and improve/change the text.

**Comment by unintendedbear** [comment]
This issue is too general. We could change it for "re-define the outline". In fact, I was about to open an issue for defining the outline and saw this issue.

**Comment by amorag** [comment]
The Issue was assigned to me because I had the general idea of what to do for this extension.

I plot my idea here, so you can define the specific Issues if you want, or you can follow another approach, of course:
- Extend the ECTA paper with a Feature Selection process (using Rough Sets on Unbalanced data):
  . Analyse the selected features. Justify them
  . Compare accuracies with the new features
  . Compare the models/classifiers (time to build it, number of rules/trees)
  . Extract example rules just using the new features (not sure if useful)
- Include a new study performing a classification without the URL field
  . the aim is to find rules without URLs (our objective in the paper). Extract some of them.
  . check the accuracies without the most important feature
- Include a new study performing a classification without the other restrictive fields (namely the IPs, and also without the URL):
  . trying to obtain more general rules (extract some examples)
  . check the accuracies in this case
- Compare the results between all these feature selection processes (automatic and manual)

Feature Selection:
- Include a paragraph in the introduction.
- Include a section in the methodology explaining the Feature Selection using Rough Sets
- Experiments and results
- Conclusions

General tasks:
- Try to focus on the CIDS Book topics => add some phrases around the whole text to better fit the paper
- Write a new abstract
- Rewrite introduction (quite similar but some new contents)
- Complete SotA with Feature Selection and with the next contents
- The paper must also comment about CI techniques in corporate security => include some contents of the GECCO paper, mainly in the state of the art section
- Better description of the data (content_type_MCT field was not commented previously)
- New comments in experiments (subsection per experiment)
- New conclusions

Take into account the restriction: "The full chapter submission must be at least 15 pages and at most 30 pages long, including tables, references, figures and appendices".

I hope this helps.

Cheers,
Antonio.

**Comment by unintendedbear** [comment]
btw, we have reached 25 pages... @zeinebchelly @amorag @JJ

**Comment by JJ** [comment]
What's the limit?

2015-02-24 17:38 GMT+01:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> btw, we have reached 25 pages... @zeinebchelly
> https://github.com/zeinebchelly @amorag https://github.com/amorag @JJ
> https://github.com/JJ
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-CIDS/issues/6#issuecomment-75792052
> .

## 

JJ

**Comment by unintendedbear** [comment]
According to @amorag :

> Take into account the restriction: "The full chapter submission must be at least 15 pages and at most 30 pages long, including tables, references, figures and appendices".

So, it seems that we're doing it right.

**Comment by JJ** [comment]
Great!

2015-02-24 17:46 GMT+01:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> According to @amorag https://github.com/amorag :
> 
> Take into account the restriction: "The full chapter submission must be at
> least 15 pages and at most 30 pages long, including tables, references,
> figures and appendices".
> 
> So, it seems that we're doing good.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-CIDS/issues/6#issuecomment-75793688
> .

## 

JJ
