### ISSUE TITLE
Rethink title

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-CIDS#8]
The title is too generic. It should describe more precisely what and how. Please @amorag and @zeinebchelly float some titles and let's settle on one.

**Comment by amorag** [comment]
- Applying Fuzzy Techniques to Improve the Management of URL Accesses in the Enterprise
- Improving a Decision System for URL Accesses in the Enterprise by means of Fuzzy Feature Selection Techniques
- Applying Feature Selection to Improve a Corporate Internet-Access Control System

Or a correct combination of them

**Comment by unintendedbear** [comment]
We had one, Zeineb and me, but I think it's better for the journal. It was "Classifying Unknown Potentially Unsecure URL Connections based on Rough Set Theory"

**Comment by zeinebchelly** [comment]
Well, actually it is not about ​fuzzy feature selection techniques... we
are not using them and rough set theory is not a fuzzy technique.
As Paloma said, I think that that title would be better for our journal
paper if the rest of you agree of course.
Based on Antonio's proposals, I propose the following title:  "Improving a
Corporate Internet-Access Control System based on Rough Set Theory"
What do you think?

2015-02-22 13:24 GMT+01:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> We had one, Zeineb and me, but I think it's better for the journal. It was
> "Classifying Unknown Potentially Unsecure URL Connections based on Rough
> Set Theory"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-CIDS/issues/8#issuecomment-75433089
> .

## 

## Kind regards,

Dr. Zeineb Chelly
Lecturer in Computer Science
University of Tunis, Department of Computer Science, Institut Supérieur
de Gestion de Tunis (ISG), 2000 Le Bardo, Tunis -TUNISIA
http://www.isg.rnu.tn/
LARODEC Laboratory, ISG-Tunis, Tunisia
http://www.larodec.com/

**Comment by unintendedbear** [comment]
Uhm, I like it, but also for the journal, hehe. I mean, here we're only improving one part, by RS for feature selection, but still we're not applying RS as classifier.
Don't mind me too much, though, I'm terrible with the titles.

**Comment by zeinebchelly** [comment]
Then, here are other proposals:
1. "Improving a Corporate Internet-Access Control System based on Rough Set
   Theory"
2. "Applying a Rough Feature Selection Technique for Improving a Corporate
   Internet-Access Control System"
3.  "An Improved Decision System for URL Accesses based on a Rough Feature
   Selection Technique"

What do you think?

2015-02-22 13:45 GMT+01:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> Uhm, I like it, but also for the journal, hehe. I mean, here we're only
> improving one part, by RS for feature selection, but still we're not
> applying RS as classifier.
> Don't mind me too much, though, I'm terrible with the titles.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-CIDS/issues/8#issuecomment-75433872
> .

## 

## Kind regards,

Dr. Zeineb Chelly
Lecturer in Computer Science
University of Tunis, Department of Computer Science, Institut Supérieur
de Gestion de Tunis (ISG), 2000 Le Bardo, Tunis -TUNISIA
http://www.isg.rnu.tn/
LARODEC Laboratory, ISG-Tunis, Tunisia
http://www.larodec.com/

**Comment by JJ** [comment]
My vote goes to 3.

**Comment by amorag** [comment]
Sorry,
I thought you use fuzzy sets as approximating sets in the RS.
That's why I included the term 'fuzzy' to catch the attention.

**Comment by zeinebchelly** [comment]
No problem :)
But fuzzy rough sets can be our next extension :)

On Monday, February 23, 2015, Antonio Mora notifications@github.com wrote:

> Sorry,
> I thought you use fuzzy sets as approximation sets in the RS.
> That's why I included the term 'fuzzy' to catch the attention.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-CIDS/issues/8#issuecomment-75470164
> .

## 

## Kind regards,

Dr. Zeineb Chelly
Lecturer in Computer Science
University of Tunis, Department of Computer Science, Institut Supérieur
de Gestion de Tunis (ISG), 2000 Le Bardo, Tunis -TUNISIA
http://www.isg.rnu.tn/
LARODEC Laboratory, ISG-Tunis, Tunisia
http://www.larodec.com/
